# -*- coding: utf-8 -*-
"""texttospeech_25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GagbwkVU2YykVeOxgpPNNCeKSHEWstUt
"""

!git clone https://github.com/nari-labs/dia.git

cd dia

pip install descript-audio-codec

import soundfile as sf
from  dia.model import Dia

model = Dia.from_pretrained("nari-labs/Dia-1.6B")

text = """[S1] You’re about to hear a voice that’s not real. I didn’t hire a voice actor I built this voice — using one of the most powerful open-source AI models on Earth.
And now I’m going to show YOU how to build it too for FREE,Let’s break the internet ."""

output = model.generate(text)

sf.write("simple.mp3", output, 44100)
import IPython
IPython.display.Audio("simple.mp3")
